### ISSUE TITLE
淘宝的运行出错，不成功

### ISSUE THREAD

**Issue by igangx** [zarkin404/sweater#22] opened 2020-06-07 06:11 UTC
VM106 TaoBao:16 Uncaught (in promise) TypeError: Cannot read property '1' of null
    at getToken (VM103 TaoBao:16)
    at signature (VM103 TaoBao:23)
    at request (VM103 TaoBao:35)
    at collectCoins (VM103 TaoBao:74)

**Comment by zarkin404** [comment] 2020-06-07 06:40
你应该未登录，或者你登录的不是淘宝的移动 h5

**Comment by zarkin404** [comment] 2020-06-07 06:41
Duplicate of #17

**Closed as completed by zarkin404** 2020-06-07 06:40 UTC
